### ISSUE TITLE
"sections" or "topics" support

### ISSUE THREAD

**Issue by jmd87fr** [danielneis/moodle-availability_paypal#12]
Hi
I try to put a Paypal  Access restrictions on a topic in Moodle 3.2 Boost theme and with firefox ans opéra
but all informations (pro mail cost names) .. are not saved
I stay on the topic setting page with a red message : You must provide a business email. You must provide a cost and it must be greater than 0. You must provide an item name. You must provide an item number.

**Comment by danielneis** [comment]
hello,

the support to sessions is not yet implemented.

**Comment by jmd87fr** [comment]
ho  yes a mistake : must read ''topic'' of course ...

**Comment by danielneis** [comment]
yes, this plugins works only with course modules, not support for sections or topics...

**Comment by jmd87fr** [comment]
Ho  ok ..
It is in your plans ?

**Comment by danielneis** [comment]
no, but if you can sponsor i can schedule to develop in january

**Comment by jmd87fr** [comment]
Ok :-) 
It's the same for activity ?

**Comment by danielneis** [comment]
for activities it is working. it should work for any course module (activities and resources)

**Comment by jmd87fr** [comment]
I resume : 
enrolment in course = OK 
Access restrictions  Activities/resources = OK
Access restrictions  Topic = NOK
right ?

**Comment by danielneis** [comment]
right

**Comment by danielneis** [comment]
hello,
I made avaialable a branch with support for sections. I made a few manual tests and it worked.
Could you please test it and let me know if it works for you?
https://github.com/danielneis/moodle-availability_paypal/tree/section-support

**Comment by jmd87fr** [comment]
Hi Daniel.
Thanks 🙂
I'll try to test it soon and I'll come back here to give you a feedback.

**Comment by ghost** [comment]
Hi

Following my tests for the issue #22 , I think this feature request is completed. 

Matt

**Comment by danielneis** [comment]
thank you!
