### ISSUE TITLE
Getting issue as : Things don't appear to be working at the moment. Please try again later. 

### ISSUE THREAD

**Issue by saianusha12345** [danielneis/moodle-availability_paypal#13]
I had installed Paypal successfully and added a restriction to an activity , when i want to make payment for that activity getting the below mentioned issue and the issue is been raised when i did the following process

1. Clicked on the payment with Paypal and then it redirected to page with amount and activity details and Send payment via Paypal button

2.**After clicking on the Send payment via Paypal button i am getting an issue as Things don't appear to be working at the moment. Please try again later.**
 

1. Can anyone of you tell me why i am getting this issue where did i go wrong 

2. Can anyone tell the Step wise instruction to use Paypal to pay for an activity

please someone help me with this

**Comment by danielneis** [comment]
This error is showed on PayPal site or Moodle? Can you attach a screenshort ?

**Comment by saianusha12345** [comment]
This is showed in  paypal site and the screenshot is below
![paypal1](https://cloud.githubusercontent.com/assets/26340332/23884624/e2b0509c-0893-11e7-8282-5abb11b70fde.PNG)

**Comment by danielneis** [comment]
Thanks.
Can you also attach a screenshot of the configuration of the restriction for the activity?

**Comment by saianusha12345** [comment]
![paypall](https://cloud.githubusercontent.com/assets/26340332/23981142/5ce6e3a2-0a2a-11e7-9a7d-441e71a4923e.PNG)
![restriction](https://cloud.githubusercontent.com/assets/26340332/23981145/629e4af6-0a2a-11e7-9594-4e0bef2df929.PNG)
![restrct](https://cloud.githubusercontent.com/assets/26340332/23981150/68e5d898-0a2a-11e7-82c8-59c76d88f6b4.PNG)
These are the screenshots of the configuration of the restriction for the activity

**Comment by danielneis** [comment]
are you sure your account is able to receive payments? have you tried with paypal sandbox ?

**Comment by danielneis** [comment]
closing as it looks like a misconfiguration issue
