### ISSUE TITLE
Nested restrictions complex logic

### ISSUE THREAD

**Issue by guanacux** [danielneis/moodle-availability_paypal#14]
![2017-05-03_1455](https://cloud.githubusercontent.com/assets/2235475/25678838/bfca236a-3010-11e7-85b7-2641838fe0cb.png)
Hi,

I wasn't able to add this restriction on a nested restriction... (to add a complex availability logic).

It only works on and/or simple conditions, not nested. (restrictions sets).

It gives the following error: 

> error/no paypal condition for this context.

Thank you!

**Comment by danielneis** [comment]
Hello,

I could not reproduce your bug, but I've added proper handling of the "not" condition now.
Please test it on the new master and submit a pull request with formal tests (behat or unit) that show it not working.
