### ISSUE TITLE
PayPal Enrollment duration

### ISSUE THREAD

**Issue by cyndikbishop** [danielneis/moodle-availability_paypal#17]
I've been able to replicate this as was brought to my attention by our client that when the enrollment duration is set to 6 months, the user is not prompted to pay again for a course but instead is automatically enrolled without having to use PayPal. I've had our technician to test as well to be sure that there was nothing on the client's site that would have caused this. He also suggests that this is a bug related issue. I've checked the trackers with Moodle HQ and am not able to find an existing one. What else do you need from me?

**Comment by danielneis** [comment]
this plugin does not support recurring payments.
this behaviour is expected.
you can made the changes in the code and send a pull request with the improvements.

**Comment by cyndikbishop** [comment]
Daniel,


Thank you for your reply. I will speak to our technicians to see if they are willing to make changes or not.


Sincerely,


Cyndi Bishop

Cyndi Bishop | Client Care Analyst | eThink Education
1111 Light Street, 4th Floor | Baltimore, MD 21230
Cyndi.bishop@eThinkEducation.com<mailto:Kara.Volpe@eThinkEducation.com>  | (817)903-7775

[cid:3cabb98f-0d2a-4703-8957-f20153d88464]


Catch us at a conference! We're attending:

Oct 10-12: 2018 CEUG Conference<http://www.cvent.com/events/2018-ceug-conference/event-summary-ff88f243ffc444c882d1e83d60bf3c4f.aspx> in Toronto

Oct 14-16: Online Learning 2018<http://globalonlinelearningsummit.ca/> / i4pl 2018<https://i4plconference.ca/> in Toronto

Oct 24-26: DevLearn<https://www.elearningguild.com/devlearn/content/5400/devlearn-2018-conference--expo--home/> in Las Vegas

Oct 29-30: U.S. MoodleMoot<https://moodlemoot.org/mootus/> in Denver

Oct 30-Nov 2: EDUCAUSE<https://events.educause.edu/annual-conference> in Denver

Nov 4 – Nov 7: Learning 2018<https://www.learning2018.com/> in Orlando




________________________________

**Comment by danielneis** [comment]
Also, be sure you are talking about the right plugin.
This one is an availability conditions, you may be talking about the enrolment plugin that is moodle core.

**Comment by cyndikbishop** [comment]
Thank you Daniel.


Sincerely,


Cyndi Bishop

Cyndi Bishop | Client Care Analyst | eThink Education
1111 Light Street, 4th Floor | Baltimore, MD 21230
Cyndi.bishop@eThinkEducation.com<mailto:Kara.Volpe@eThinkEducation.com>  | (817)903-7775

[cid:5bfc269d-a40b-4c6b-944e-c6e5e40a82e7]


Catch us at a conference! We're attending:

Oct 10-12: 2018 CEUG Conference<http://www.cvent.com/events/2018-ceug-conference/event-summary-ff88f243ffc444c882d1e83d60bf3c4f.aspx> in Toronto

Oct 14-16: Online Learning 2018<http://globalonlinelearningsummit.ca/> / i4pl 2018<https://i4plconference.ca/> in Toronto

Oct 24-26: DevLearn<https://www.elearningguild.com/devlearn/content/5400/devlearn-2018-conference--expo--home/> in Las Vegas

Oct 29-30: U.S. MoodleMoot<https://moodlemoot.org/mootus/> in Denver

Oct 30-Nov 2: EDUCAUSE<https://events.educause.edu/annual-conference> in Denver

Nov 4 – Nov 7: Learning 2018<https://www.learning2018.com/> in Orlando




________________________________
