### ISSUE TITLE
INR payments

### ISSUE THREAD

**Issue by RekhaC** [danielneis/moodle-availability_paypal#18]
INR (Indian Rupee) payments are allowed by PayPal now.  

1) INR is now showing in the drop down

2) I have USD - suppose i want to give the option of USD and INR - can i have 2 buttons/ 2 plugins? 
How does it work? Am i supposed to have only one currency?

**Comment by danielneis** [comment]
You will have to add two instances of the plugin, one with each currency.
PayPal may restrict which currencies you may use.
