### ISSUE TITLE
PayPal SCORM Activity Restrict Access Logic

### ISSUE THREAD

**Issue by jeffnowlearn** [danielneis/moodle-availability_paypal#19]
Hi
I am trying to use the restrict access within a SCORM Package activity but it does not work – I am trying to restrict access to different users belonging to specific groups using the OR statement .  When I add an additional OR to include PayPal enrollment it  does not work.  However, with a label activity I have restricted this to users with PayPal enrollment and it does work.  Also can you confirm the rules relating to the fields in Restrict Access :PayPal Payment
1) business email -= PayPal business email and is mandatory
2) Currency = I set this to British Pounds same as the course fee – is this mandatory if so this would mean we could only have one currency per course
3) Cost = is this mandatory as we have different fees for the same course?
4) Item name – this appears to be mandatory but is a free text field which can be any value
5) Item number - this appears to be mandatory but is a free text field which can be any value

**Comment by danielneis** [comment]
Hi,

1. Business email - PayPal business email, is mandatory, right
2. Currency - It is mandatory and paypal have it's own rules on which users can use which currencies in which countries
3. Cost - it is mandatory and you can only have one cost per enrol instance. If you have different costs, create different enrol instances. If you have differente costs in different currencies, create different instancies too.
4. It is not mandatory, only if you can change the Item name that will appear on PayPal.
5. Same as item name, but for the item number on paypal.

Can you be more specific on what does not work when you include this condition with other codition using the OR operator?

**Comment by jeffnowlearn** [comment]
Hi

 

Hi thanks for the response

 

I am use the or statement to restrict access to items in the Course Topic Screen for example (this example illustrates the rules I am using in my work)

 



 

 

What I tried to do is restrict access in a SCORM Activity to only users that had enrolled by PayPal (your plugin) OR  belonged to a Group “001 Live”.  However a user that enrolled by PayPal who did not belong to the Group “001 Live” did not see the SCROM ACTIVITY.

 

To test the logic I did use a Label activity with the same settings I used to configure the PayPal fields (these were consistent with your comments in the email) to display text on the Topic section.  This did work for the same user enrolled by PayPal who did not belong to the Group “001 Live”.

 

So using the same field values and logic I got the Label Activity to display but not the SCORM file Activity to display for the same user.

 

Does that help explain?

 

Jeff

**Comment by danielneis** [comment]
this plugin is not about paypal enrolment. this is about requiring users to make a payment using paypal to access an activity or resource, after he/she is enrolled by any method.
this plugin should work with all activity plugins, please, review your setup.
