### ISSUE TITLE
error can't access to activity after pay 

### ISSUE THREAD

**Issue by TNDdesarrollo** [danielneis/moodle-availability_paypal#20]
Hi, I installed this plugin in moodle 3.6 and I used in activity Big Blue Button but when the users pay they can't access to the activity.

**Comment by danielneis** [comment]
Hi. Can you share what happens after the payment? It was confirmed on PayPal ? The user is redirect back? It would be nice if you can share some screenshots

**Comment by akasaj** [comment]
Hi. I have the same problem as TNDdesarrollo. The user pays through paypal and the payment is confirmed, but the user does't get acces to the activity.

**Comment by danielneis** [comment]
can you enable debug and send some screenshots of error or warning messages?

**Comment by pedro-henrique-brandao** [comment]
Olá Daniel, Estou com o mesmo problema na moodle versão 3.6.2+
O pagamento ocorre tudo ok
mas quando clico no botão pra voltar a plataforma a atividade continua bloqueada.
IPN configurado
UTF ok
me ajuda?

**Comment by danielneis** [comment]
Olá, Pedro
você pode confirmar para qual url você configurou o retorno do paypal? E você está usando HTTPS no seu site? Isso é um requisito do paypal...

**Comment by pedro-henrique-brandao** [comment]
Olá, Daniel.
Parabéns pelo excelente trabalho desenvolvendo esse plugin.

URL de retorno do paypal seria a Notificação instantânea de pagamento (NIP)?
se for, https://rhitmo.com.br/availability/condition/paypal/ipn.php
protocolo https configurado.

**Comment by danielneis** [comment]
Ao voltar do PayPal o usuário cai em qual página? Tem alguma mensagem de erro? Já fez com o debug habilitado?

**Comment by pedro-henrique-brandao** [comment]
ele cai na página da atividade na etapa de clicar no botão do paypal para efetuar o pagamento novamente.
vou efetuar o processo com o debug ativado e posto aqui.

obrigado

**Comment by pedro-henrique-brandao** [comment]
Fiz todo o procedimento com o debug habilitado, não ocorre nenhum erro, como devo proceder?
a atividade continua bloqueada...
versão da moodle 3.6.2+

**Comment by pedro-henrique-brandao** [comment]
volta para essa URL
https://rhitmo.com.br/availability/condition/paypal/view.php?contextid=185

**Comment by danielneis** [comment]
Disponibilizei uma nova versão aqui no github que deve ser compatível com a 3.6, 3.7 e 3.8.
Podes testar, por gentileza?

**Comment by danielneis** [comment]
please, take a look at #12 and #22, there's a new version that fix the plugin
