### ISSUE TITLE
Error after setting up

### ISSUE THREAD

**Issue by mathgic** [danielneis/moodle-availability_paypal#22]
I have set up an activity restrictions of Paypal and setup a cost. Then I login as student user and I see the "you make a payment with PayPal" the link should be pointing at this url: https://mathgic.hk/365/availability/condition/paypal/view.php?contextid=277. Then when I clicked the link, it shows an error message: "error/no paypal condition for this context." There is another message underneath it, "More information about this error". It redirects me to moodle doc, "This page does not exist yet. You can search for this page title in other pages, or let us know by posting about it in one of the Moodle community forums." Can you tell me what's the next thing I should do or I should have done? Many thanks.

**Comment by gusgura** [comment]
I have the same issue, and i don't know if its the IPN configuration or anything else.

**Comment by danielneis** [comment]
Hi, I made available here on github a new version that may be compatible with Moodle 3.6 onwards. Could you please test it and let me know if it works for you?

**Comment by Boti123** [comment]
Hi I am also having this issue? Any help?

**Comment by ghost** [comment]
Hi Daniel

I found the same issue, at the activity level:
![2020-06-03 20_43_59-Window](https://user-images.githubusercontent.com/58011947/83683808-dea60880-a5dd-11ea-9b18-29cd233fc921.png)

And an "error/support to sections not yet implemented." error message at the section level:
![2020-06-03 20_44_13-Window](https://user-images.githubusercontent.com/58011947/83683844-ebc2f780-a5dd-11ea-92d0-06fdd8d04b51.png)

I've installed the latest version 8 of the plugin, from moodle.net website.

The IPN URL was set on a personal PayPal account for testing. To ensure that it wasn't the reason, I deactivated the PayPal enrolment plugin and used the business PayPal account, putting https://my.domain.com/availability/condition/paypal/ipn.php but still no success.

I downgraded to version 4 and tested from version 4 to 7 but I still had the same message.

All the fields are filled, the email address does match the one for the PayPal account.

The website is fully HTTPS and is on the latest Moodle version (Moodle 3.8.3+; Build: 20200512)

I can't see what goes wrong.

Any way to get help on this? Or anything else you need to solve this issue?

**Comment by ghost** [comment]
Quick update, I've installed the section branch instead and it works at the section level. Still, no luck at the activity level.

**Comment by danielneis** [comment]
Hi,
thank you for your report.
I just release a new version with the section support and fixes for the activity level.
Please, let me know if that works for you.

**Comment by ghost** [comment]
Hi Daniel

I've tested the version 10 and confirm that it works both at the section and activity level.

Thanks for the fix.

Regards
Matt

**Comment by danielneis** [comment]
thank you!
