### ISSUE TITLE
Available for Moodle 3.7 and 3.8?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [danielneis/moodle-availability_paypal#23]
Hi,
According to the 'Stats' tab in the plugin page at https://moodle.org/plugins/availability_paypal, quite a few Moodle sites seem to be using this plugin for Moodle 3.7, even though it is not officially marked as supported for such Moodle branch.

Can you please test it and mark as supported for Moodle 3.7 and Moodle 3.8.

Thanks in advance.

**Comment by danielneis** [comment]
Hi, German

I could not test it on 3.7 and 3.8 right now, but I updated the plugin in the directory to support 3.7 and 3.8. Please, let me know if you have any issues on those versions.

Best regards,
Daniel

**Comment by germanvaleroelizondo** [comment]
Thanks Daniel.
