### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lucialence** [danielneis/moodle-availability_paypal#24]
When I pay with paypal it redirect to the activity in moodle but it doesn't recognize the payment.

This is the error log.

500 POST /availability/condition/paypal/ipn.php PayPal IPN

Warning FastCGI sent in stderr: &quot;PHP message: PHP Warning: require_once(/var/www/vhosts/moodle.prueba.edu/httpdocs/lib/eventslib.php): failed to open stream: No such file or directory in /var/www/vhosts/moodle.prueba.edu/httpdocs/availability/condition/paypal/ipn.php on line 36&quot; while reading response header from upstream

Can anyone help me?

**Comment by danielneis** [comment]
Hi, I made available a new version here on github that may be compatible with 3.6 onwards. Could you please test it and let me know if it works for you?

**Comment by lucialence** [comment]
Hi Daniel,

I´ve just test the new version on Moodle 3.8.1 and it works fine.

Thank you so much¡
