### ISSUE TITLE
Paying for one section unlocks all the others blocked

### ISSUE THREAD

**Issue by Maniup** [danielneis/moodle-availability_paypal#29]
Using the plugin on different sections of the same course. Using same account (paypal email) for payments, even if you set different item name, item number and price, if you unlock one section, it automatically unlocks the others as well.

moodle version: 3.6.3 
Plugin version: 11 (2020072100)

**Comment by danielneis** [comment]
Hello,
I've made available a new version that must fix this issue.
Would you please try it and report if it works?
Best,
Daniel
