### ISSUE TITLE
Form field validation

### ISSUE THREAD

**Issue by meridiumtechnologies** [danielneis/moodle-availability_paypal#3]
Settings are not validated, e.g. one can enter text string for the _Cost_.

**Comment by meridiumtechnologies** [comment]
The "Cost"  field is still not validating (float) as I was able to enter and save free text.

**Comment by danielneis** [comment]
hello, now i've managed to fix the validation based on what is done on the "grade" availability condition =)

**Comment by meridiumtechnologies** [comment]
+1
