### ISSUE TITLE
Error code: no paypal condition for this context.

### ISSUE THREAD

**Issue by smcpaiva** [danielneis/moodle-availability_paypal#30]
Hi Daniel, how are you?
The availability condition PayPal by "cohort" displays this error code: no paypal condition for this context.
Error code: no paypal condition for this context.
line 498 of /lib/setuplib.php: moodle_exception thrown
line 56 of /availability/condition/paypal/view.php: call to print_error()

We use Moodle 3.9 and availability_paypal 2021030400

I appreciate your attention. Thank You!

**Comment by smcpaiva** [comment]
Hello again.
The problem occurs when the condition PayPal is added within the "RESTRICTION GROUP", and is not related to the cohort.

**Comment by danielneis** [comment]
Hello,
I've added a fix for when using restriction groups.
