### ISSUE TITLE
Change Default text

### ISSUE THREAD

**Issue by LukeDuffy98** [danielneis/moodle-availability_paypal#34]
Hi

Is it possible to configure the value : eitherdescription

I can see the value in the file /lang/en/availability_paypal.php
![image](https://user-images.githubusercontent.com/31847926/127100008-05105d4e-e093-42cd-bff6-e9fee8dc2aa8.png)

What I would like to see is something like this:
![image](https://user-images.githubusercontent.com/31847926/127099919-29907f5f-c878-4903-bb92-ee53cbeba1ca.png)

rather than the defualt
![image](https://user-images.githubusercontent.com/31847926/127099941-9a62522f-a51f-4b54-b144-a0d4569b144a.png)

Thanks
Luke

**Comment by danielneis** [comment]
You can go to Site administration / Language / Language customisation and change it.
https://docs.moodle.org/311/en/Language_customisation

**Comment by LukeDuffy98** [comment]
Fantastic !!!!

Thank you very much for that
