### ISSUE TITLE
Selectors for currencies

### ISSUE THREAD

**Issue by meridiumtechnologies** [danielneis/moodle-availability_paypal#4]
Currencies should be presented as a selector instead of input text.

**Comment by meridiumtechnologies** [comment]
Am I right to assume that we cannot use Moodle API to generate the list of currencies (selector) as it doesn't use the same convention as Paypal? Doesn't matter in my case but I am thinking of the community. It seems harsh to hard code this info in the plugin...

**Comment by danielneis** [comment]
Yes, it is a good idea.
I've made a commit that does that =)
